# This is a basic workflow to help you get started with Actions

name: Code Coverage
env: # Or as an environment variable
  CODECOV_TOKEN: '${{ secrets.CODECOV_TOKEN }}'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      
      # the action needs a nightly toolchain with llvm-tools
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: llvm-tools-preview

      # runs cargo with defaults flags, using the default `lcov` output
      - uses: Swatinem/fucov@v1

      # afterwards, upload the report to codecov
      - uses: codecov/codecov-action@v1
        with:
          directory: coverage
